### ISSUE TITLE
Implement git submodules for covid-datastoring

### ISSUE THREAD

**Issue by PetKosTuni** [PetKosTuni/Epidemic-model-of-COVID#18]
Investigate whether or not move covid data to separate repository and implement git submnodules.

Documentation https://git-scm.com/docs/gitmodules

Implementation would look something like this:

```
[submodule "coviddata"]
	path = data
	url = git://foo.com/git/lib.git
```

**Comment by sampozki** [comment]
Implemented in https://github.com/PetKosTuni/Epidemic-model-of-COVID/pull/30
