### ISSUE TITLE
Solve crashing problem of JHU data

### ISSUE THREAD

**Issue by Snibz** [PetKosTuni/Epidemic-model-of-COVID#22]
Look at telegram for details. JHU_global crashes in data.py, if temporary fix that is currently commented out is implemented, then the program crashes when training the model in rolling_train_modified.py. THis means that at least JHU nation level data cannot be used with the model, which is a problem. Look into this, try to make JHU datasets work.

**Comment by JoonasPel** [comment]
Crashing in rolling_train_modified.py happened because the target array were dtype 'O' (Object), instead of float64 like the pred array. I added a new function ensure_float64() that checks that both arrays are dtype float64 and if not, converts them.

**Comment by JoonasPel** [comment]
The fix raised a new warning inside data.py/JHU_global/get:
data.py:141: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date = pd.to_datetime(self.confirm_table.index[1:])
 
 I will add fix to this

**Comment by JoonasPel** [comment]
Fixing this more. Found out that --level states still doesn't work.

**Comment by JoonasPel** [comment]
Forgot to close this issue. Closing it now.
