### ISSUE TITLE
Investigate package functionalities

### ISSUE THREAD

**Issue by PetKosTuni** [PetKosTuni/Epidemic-model-of-COVID#74]

**Comment by sampozki** [comment]
This seems to be pretty complicated.

Not sure how it would be smart to implement.

In my opinion cloning or downloading this repository would be much easier than using pip to "install" this code. But the customer wanted this so might as well...

**Comment by sampozki** [comment]
We discussed with our customer that simple zip file would work fine. Most important thing is that downloading code is easy. We really can't create a exe file that runs everything.

Lets just provide an easy guide how to download zip file from github.
